
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      touch /tmp/.npm-lock
      npm install
      npm run prepare
      npm update
      npm audit fix
      npm install -g @vue/cli
      rm /tmp/.npm-lock
  - init: |
      echo "Waiting for npm install to complete"
      sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: |
      echo "Starting Ambianic UI in dev mode:"
      npm run serve
  - init: |
      echo "Waiting for npm install to complete"
      sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
      gp await-port 8080 && gp preview $(gp url 8080)/index.html
      echo "Waiting for Ambianic UI to start"
    command: |
      echo "Starting Ambianic PWA testsuite"
      npm run test
  - init: |
      echo "Waiting for npm install to complete"
      sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
      gp await-port 8080 && gp preview $(gp url 8080)/index.html
      echo "Waiting for Ambianic UI to start"
    command: |
      echo "Starting Cypress in Interactive Mode"
      npm run cy:open
  - init: |
      echo "Starting Browsersync"
  - command: |
      echo "Starting http server for local HTML file preview"
      npx browser-sync start -s -w

# vscode:
#  extensions:
#    - octref.vetur@0.31.3:QHyAEoimIBiRDoL6WtEoRg==

ports:
  - port: 8080 # Ambianic UI App
    onOpen: open-browser
  - port: 6080 # Cypress Interactive Mode
    onOpen: open-browser
  - port: 3000 # Static file serve via Browsersync
  - port: 3001 # Browsersync dashboard
  - port: 8888 # Dependencies chart
  - port: 10000
    onOpen: ignore
  - port: 5900
    onOpen: ignore


github:
  prebuilds:
    addComment: true


vscode:
  extensions:
    - octref.vetur