name: CI for Ambianic UI 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm version
        npm install -g npm
        npm version
        npm ci
      env:
        CI: true
    - name: End-to-end Tests with Cypress
      uses: cypress-io/github-action@v1
      with:
        start: npm run serve
        record: true
        wait-on: 'http://localhost:8080'
      env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage/coverage-final.json # optional
        flags: pwa-e2e-cypress-tests # optional
        name: pwa-e2e-test-coverage # optional
        fail_ci_if_error: true # optional (default = false)        
    - name: Build PWA distribution for production
      run: |
        npm run build --if-present
      env:
        CI: true
    - name: Semantic Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Lighthouse CI
      uses: treosh/lighthouse-ci-action@v2
      with:
        configPath: '../../lighthouserc.json'
        temporaryPublicStorage: true
